server:
  port: 8050
eureka:
  client:
    serviceUrl:
      defaultZone=http://localhost:8761/eureka/:
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: customer
          uri: http://localhost:7778/
          predicates:
            - Path=/customer/**